version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # node_modules volume
      - side-by-side-modules:/app/node_modules
      # bind mount of host's blog directory
      - .:/app
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1

volumes:
  side-by-side-modules: