version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      - side-by-side-modules:/app/node_modules
      - .:/app
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1

volumes:
  side-by-side-modules: